apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-sessions-job
spec:
  schedule: "0 0 * * 0"
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 20
      template:
        spec:
          containers:
            - name: clear-sessions-container
              image: alex662/django_app:minikube
              imagePullPolicy: IfNotPresent
              command: ["python", "manage.py", "clearsessions"]
              envFrom:
                - secretRef:
                    name: django-app-secret
          restartPolicy: OnFailure